spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test-system?serverTimezone=GMT%2b8
    username: qian
    password: 123456
service:
  port: 80

  thymeleaf:
    cache: false

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleteFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
# 验证码配置
kaptcha:
  height: 36
  width: 110
  content:
    length: 4
    source: 123456789
    space: 3
  font:
    color: black
    name: Arial
    size: 30
  background-color:
    from: lightGray
    to: white
  border:
    enabled: false